// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_chirp.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getChirp = `-- name: GetChirp :one
SELECT id, body, created_at, updated_at, user_id 
  FROM chirps
  WHERE id = $1
`

type GetChirpRow struct {
	ID        uuid.UUID
	Body      string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
}

func (q *Queries) GetChirp(ctx context.Context, id uuid.UUID) (GetChirpRow, error) {
	row := q.db.QueryRowContext(ctx, getChirp, id)
	var i GetChirpRow
	err := row.Scan(
		&i.ID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}
