// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: list_chirps.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listChirps = `-- name: ListChirps :many
SELECT id, body, created_at, updated_at, user_id FROM chirps 
  ORDER BY created_at ASC
`

type ListChirpsRow struct {
	ID        uuid.UUID
	Body      string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
}

func (q *Queries) ListChirps(ctx context.Context) ([]ListChirpsRow, error) {
	rows, err := q.db.QueryContext(ctx, listChirps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChirpsRow
	for rows.Next() {
		var i ListChirpsRow
		if err := rows.Scan(
			&i.ID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
